# Task writes "some stuff" to a predefined path in the workspace git PipelineResource hi bog9
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-file
spec:
  inputs:
    params:
      - name: channel
        default: taskdefault
  steps:
  - name: read-docs-old
    image: ubuntu
    command: ["/bin/bash"]
    args: ['-c', 'echo $(inputs.params.channel)'] # tests that targetpath works
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: output-pipeline
spec:
  params:
  - name: channel
    default: pipelinedefault
  tasks:
  - name: first-create-file
    taskRef:
      name: create-file
    params:
      - name: channel
        value: $(params.channel)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: channel
      description: templatedefault
      default: templatedefault
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: issue11640
      spec:
        params:
          - name: channel
            value: $(params.channel)
        pipelineRef:
            name: output-pipeline
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pipeline-binding
spec:
  params:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: pipeline-binding
      template:
        name: pipeline-template
      params:
